services:
  api-librix:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker123
      - POSTGRESQL_DATABASE=apiLibrix
